# Generated by Django 2.0.7 on 2018-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
