# Generated by Django 2.0 on 2018-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivestars',
            name='image',
            field=models.ImageField(upload_to='images/5/'),
        ),
        migrations.AlterField(
            model_name='fourstars',
            name='image',
            field=models.ImageField(upload_to='images/4/'),
        ),
        migrations.AlterField(
            model_name='threestars',
            name='image',
            field=models.ImageField(upload_to='images/3/'),
        ),
    ]
